language: node_js
services:
- docker
node_js:
- 10.0.0
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - TRUNK_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlabllc"
  - CHART="fe"
  - secure: g0ucSJW6qgwUa9BPockDpCVb2nhkvzaEmZvh0EIkr+10bImhI086g+ytiqxxBCbIzL7qSOtp+Sr8iwZwrwk6qI16sGmTzvy/BOtSSL2fevapdhgQRXn7JDaaj19pQ8xgo3hkyjkGsHr22/27uD88AlwG8Wv0nhV5oH0Kb/reOjv1QrF+oRtjVrpRRw0PL5rFLYZ/JZ7kkdVI+pp2aDTIEJs/QxSsJ602fokuLbwdrNKeo3BQEnzY95Z0TYaj9Rvl8nI3a/LECNeKABHLVhn0t4qXQBqIZmR/3Il3QOA1eUAoNarsZsuGKweEnKYbj0X6F19tjRupYdHY25W42MUxvun4VJ/AzXLRaa4KdiCAGn5k99jlpIUHOu+NnnUSppac+39qoepridJ4vPiqhNpHHTtfui6eKvF3WSx+znzwM41c1jv/bjZ9SfYuvoXLbCyQzgZrCJEDP3iRJpaTkasfXTdwSmAIbHDVZEU1jic1zLYIyjxzuGG2oV0c37M5AgdzsL/HiqOSVh5zetMH2N76MbQ4bjUtm7+pjUpD5Vinuya6VmHe8vIQwe3aDPEiNozE5XD6uABtHIYcsGTky2a319GOiCWNHpT4/7r3kqpqMQIdNnhfQq7TWoaGz77L7RaBIdsmqDQ3C2xF/3FoGlr1Vv8Olm0v2fWQTXIyJKv7th8=
  - secure: Vlp9QazReDIv234C1/zjPyJIwm/RjBRLMu0Qmpsy1C7h7NIQvd9xlutgzGDw2xP0NCj2p9kThW+rGoi8PSGObJJHuv5uuqoa22BHoXdenDgN6/AOf6iJexup7T98pIlBskbkdiaJSMf4J+cSQ9tJizOIL9timOP14iAyMtUltM1EsaFEoSMWHnDu1oE50R4aMHvdSUnO+jzkLhGBPrHZMZDMkeVDIv+qaGnwr9s3l+emI9x+cSxKybM+OwEJpa/ZycxuuPgsjsrWzMcvNLF+qGsMFXl8BnigQmKauc7UzcRQx3qO9zkyAhvQSQHSFnBeMmdjkjkd7vdFRO90bnI1mHYj5UmV6+v8nqVSsz/gHUaeBPNEexpy83GPe7iQO1Xh0iMZRB8GRyqcsmsHFKaszh+C4i+6vZduvy5HbZ0djOa8nJnLHV9euffY9jvetbZQmsoRCbUPW0Ih/iYXfUauLl1DelgU/kyFQ9Lg/ynwBE477A17NQk3shzvQHS8pGvd6DdXxgkWB0XFfEW2japQoAXvDQ/EN0XCvZXMoQPKngLvEGFW5BmsntjuHhyKiUSY/pBF6klaAalASGi/Jgft5yE0gCtsZSVv4xN8sSbU2//jT525jxgkcAh8KrdmwwnG3G11S2f9qjwY7oKWPYQg8Z+rPfjimYsRUZXg8dBQZ7A=
  - secure: FBlFqxWej/gWqnvBa3ah451ItzBpE7RQX2j2Eyv0ABE6OdSiAlUMimTAhVmawA5R4F7DDFmSKeY9L6zD/qKz+OtcuI6ATxGlDRy8puff27UQJtYeIQDDMyUKWwRk+dsZgbu0sbYvv5D5/+cOodusVtaN4bvlV1OPNNVkXgGOOJmGxsZwHw7mJJM49L/ufdPv+WNa+zrDERBe9HAgQ48G98S1Q0P8SF2GzIoBJgP1Id+VXM7yUK1OC3oHtO/5mxV++T88O5VtY0ISeYmfSAp7IIbYYQXPnh4NWb5iFGBx3epjeQVfSoUDlD9UOhsphChhJeaQwvsb7X0pmM5lW1eDnoXZNcP2g6cvZz6dPaiZvbMd8ZwS1JMOb8KFSEWtUAid2i8J6OfMgp1QQ34T5duO8UPc2z6AVuRIot+NQw5eGt1JQ5uXJEre+VmEJfcrkfQDaGmdJoyOWnGFKq+XURgdPW4cmBAB8Bx6QYqOCRlSy0+8kJiBMSFTe2Z/Ay4hoASyUlcWlCHLlywRWELip5T3V5ZByC79Zp9mBCx3g7LzbfK2ntCJBJWn9M+ucPeH9JARwJ2cjObau/dpiXZeFOzMIsTPmjuUN/5wXn3CkoqNZ3i1VDTG5b++3o8VVKMVqhT5COdVXczLiWiigxTmJtYPhQiGEuMgClwvFIAhmymOZW4=
install:
- npm ci
- npx lerna bootstrap --ci
script: npm test
before_deploy:
- git config --global user.email "deploy@travis-ci.org" &&
  git config --global user.name "Deployment Bot" &&
  git config --global credential.helper "store"
- echo "https://${GITHUB_TOKEN}:@github.com" > $HOME/.git-credentials
- git checkout $TRAVIS_BRANCH
- echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
- openssl aes-256-cbc -K $encrypted_d422cd97315f_key -iv $encrypted_d422cd97315f_iv -in eHealth-d14f79f426fb.json.enc -out eHealth-d14f79f426fb.json -d
- gcloud auth activate-service-account --key-file=$TRAVIS_BUILD_DIR/eHealth-d14f79f426fb.json &&
  gcloud container clusters get-credentials dev --zone europe-west1-d --project ehealth-162117
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
- git clone https://github.com/edenlabllc/ehealth.charts.git charts
deploy:
  provider: script
  script: 'npm run publish -- --yes -m "chore(release): publish %s [skip ci]"'
  skip_cleanup: true
  on:
    condition: "$TRAVIS_BRANCH =~ (^$TRUNK_BRANCH|[[:digit:]]-stable)$"
after_deploy: npm run update-chart && npm run deploy-chart
