schemaVersion: 2.0.0
fileExistenceTests:
  - name: nginx.conf
    path: /etc/nginx/nginx.conf
    shouldExist: true
  - name: index.html
    path: /usr/share/nginx/html/index.html
    shouldExist: true
  - name: static
    path: /usr/share/nginx/html/static
    shouldExist: true
